services:
  mysql:
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    profiles:
      - mysql

  database:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER:-petclinic}
      - POSTGRES_DB=${DB_DATABASE:-petclinic}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-petclinic}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${DB_DATABASE:-petclinic}"]
      interval: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql

  app:
    build:
      context: .
      dockerfile: Dockerfile-multi_stage
    environment:
      - POSTGRES_URL=${DB_URL:-jdbc:postgresql://database/petclinic}
      - POSTGRES_USER=${DB_USER:-petclinic}
      - POSTGRES_PASS=${DB_PASSWORD:-petclinic}
      - DATABASE=postgres
      - SPRING_PROFILES_ACTIVE=postgres
    healthcheck:
      test: curl localhost:8080
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - deps:/home/myuser/.m2
    ports:
      - "8080:8080"
volumes:
  postgres_data:
  deps:
